/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: "rgb(var(--ink) / <alpha-value>)",
        "ink-soft": "rgb(var(--ink-soft) / <alpha-value>)",
        paper: "rgb(var(--paper) / <alpha-value>)",
        "paper-2": "rgb(var(--paper-2) / <alpha-value>)",
        foam: "rgb(var(--foam) / <alpha-value>)",
        line: "rgb(var(--line) / <alpha-value>)",
        "line-2": "rgb(var(--line-2) / <alpha-value>)",
        sun: "rgb(var(--sun) / <alpha-value>)",
        "sun-hot": "rgb(var(--sun-hot) / <alpha-value>)",
        sky: "rgb(var(--sky) / <alpha-value>)",
        "sky-deep": "rgb(var(--sky-deep) / <alpha-value>)",
        mute: "rgb(var(--mute) / <alpha-value>)",
        faint: "rgb(var(--faint) / <alpha-value>)",
        alert: "rgb(var(--alert) / <alpha-value>)",
        roast: "rgb(var(--roast) / <alpha-value>)",
        "roast-2": "rgb(var(--roast-2) / <alpha-value>)",
        "line-dark": "rgb(var(--line-dark) / <alpha-value>)",
        cream: "rgb(var(--cream) / <alpha-value>)",
        "cream-soft": "rgb(var(--cream-soft) / <alpha-value>)",
        gold: "rgb(var(--sun) / <alpha-value>)",
        turq: "rgb(var(--sky) / <alpha-value>)",
        crema: "rgb(var(--sun) / <alpha-value>)",
        rust: "rgb(var(--alert) / <alpha-value>)",
        pine: "rgb(var(--sky) / <alpha-value>)",
        stone: "rgb(var(--paper) / <alpha-value>)",
      },
      fontFamily: {
        display: ['"Marcellus"', "Georgia", "serif"],
        sans: ['"Manrope"', "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ['"IBM Plex Mono"', "ui-monospace", "monospace"],
      },
      borderRadius: {
        none: "0",
        sm: "0",
        md: "0",
        lg: "0",
        xl: "0",
      },
    },
  },
  plugins: [],
};
